[tools]
npm = "latest"
node = "lts"

[tasks]
build = "docker build --progress=plain -t seahax/devcontainer ."
buildx = "docker buildx build --progress=plain --platform linux/arm64,linux/amd64 -t seahax/devcontainer ."
