[env]
AWS_PROFILE = "seahax"
AWS_REGION = "us-west-2"

[tasks.build]
run = "docker build --progress=plain -t seahax/devcontainer ."

[tasks.buildx]
run = "docker buildx build --progress=plain --platform linux/arm64,linux/amd64 -t seahax/devcontainer ."
