[tools]
npm = "latest"
node = "lts"
doctl = "latest"
aws = "latest"
"npm:@anthropic-ai/claude-code" = "latest"

[env]
AWS_PROFILE = "seahax"
AWS_REGION = "us-east-1"
AWS_PAGER = ""

[tasks]
build = "docker build --progress=plain -t seahax/devcontainer ."
buildx = "docker buildx build --progress=plain --platform linux/arm64,linux/amd64 -t seahax/devcontainer ."

[tasks.devcontainer_init]
hide = true
run = [
  "ln -s -t ~ /mnt/home/.aws",
  "ln -s -t ~/.config '/mnt/home/Library/Application Support/doctl'",
  "ln -s -t ~ /mnt/home/.npmrc",
  "npm install",
]
