run-name: ${{ github.workflow }}

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - ".devcontainer/**"
      - "README.md"
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ github.workflow }}${{ github.event_name == 'pull_request' && '-pr' || '' }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-qemu
        uses: docker/setup-qemu-action@v3

      - name: setup-buildx
        uses: docker/setup-buildx-action@v3

      - name: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request'}}
          secrets: github_token=${{ secrets.GITHUB_TOKEN }}
